services:
  # web:
  #   build: .
  #   ports:
  #     - "80:8081"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["python", "app.py"]
 
  db:
    build: ./db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./dev.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD", “pg_isready”]
    #   interval: 30s
    #   timeout: 5s
    #   start_period: 15s
    #   retries: 10
  
  functions:
    build: ./api
    ports:
      - "8081:80"
    volumes: 
      - ./api:/home/site/wwwroot
    env_file:
      - ./dev.env
    # depends_on:
    #   db:
    #     condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
secrets:
  db_password:
    file: ./db/db_password
 
volumes:
  pgdata:
 